name: Secure CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Ejecutar Semgrep
        run: |
          mkdir reports
          semgrep scan --config auto --json --output reports/semgrep.json .

      - name: Escaneo con Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          output: reports/trivy.txt

      - name: Guardar reportes
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: reports/
